# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Server
version:      0.22
version_from: lib/Catalyst/Plugin/Server.pm
installdirs:  site
requires:
    Catalyst:                      5.66
    RPC::XML:                      1.35
    RPC::XML::Parser:              1.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
